export const authConstants={
	SET_AUTH_DETAILS: "SET_AUTH_DETAILS",
	UPDATE_PROFILE_PICTURE: "UPDATE_PROFILE_PICTURE",
	UPDATE_PROFILE_PICTURE_SUCCESS: "UPDATE_PROFILE_PICTURE_SUCCESS",
	UPDATE_PROFILE_PICTURE_FAILURE: "UPDATE_PROFILE_PICTURE_FAILURE",
}