export const registrationConstants = {
    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGISTER_FAILURE",
    ERROR_UPDATE: "ERROR_UPDATE",
    ERROR_MSG_UPDATE: "ERROR_MSG_UPDATE",
    UPDATE_USERDETAILS: "UPDATE_USERDETAILS"
};
