export const ordersConstants = {
	GET_ORDERS_COMPLETED: 'GET_ORDERS_COMPLETED',
	GET_ORDERS_UPCOMING: 'GET_ORDERS_UPCOMING',
	GET_ORDERS_PENDING: 'GET_ORDERS_PENDING',
	GET_ORDERS_DECLINED: 'GET_ORDERS_DECLINED',
	SET_ORDERS_COMPLETED: 'SET_ORDERS_COMPLETED',
	SET_ORDERS_UPCOMING: 'SET_ORDERS_UPCOMING',
	SET_ORDERS_PENDING: 'SET_ORDERS_PENDING',
	SET_ORDERS_DECLINED: 'SET_ORDERS_DECLINED',
	ACCEPT_DECLINE_SERVICE: "ACCEPT_DECLINE_SERVICE",
	SUCCESS_ACCEPT_DECLINE_SERVICE: "SUCCESS_ACCEPT_DECLINE_SERVICE",
}